### ISSUE TITLE
Speed: normalized by batch size?

### ISSUE THREAD

**Issue by vadimkantorov** [jcjohnson/cnn-benchmarks#13]
Hi,

Are the speed numbers divided by the mini-batch size ( = 16)?

From what I can see (https://github.com/jcjohnson/cnn-benchmarks/blob/master/cnn_benchmark.lua#L46), it is not normalized. Is it correct?

Thanks,
Vadim

**Comment by jcjohnson** [comment]
No it is the speed for the entire mini batch

**Comment by vadimkantorov** [comment]
Thanks for a quick response. A note in the main text about it wouldn't hurt though. All in all, very nice work, thanks for making it available!

**Comment by unixpickle** [comment]
Glad I found this issue. I was wondering the same thing.
