### ISSUE TITLE
convert_model.lua Usage

### ISSUE THREAD

**Issue by DavidFreebairn** [jcjohnson/cnn-benchmarks#19]
Having issues trying to use convert_model.lua to convert VGG_ILSVRC_19_layers.caffemodel to a .t7 file for use with fast_neural_style.lua.

Here is an example of my terminal command:

sudo th convert_model.lua -input_prototxt '/home/david/Deepstyle/cnn-benchmarks/VGG_ILSVRC_19_layers_deploy.prototxt' -input_caffemodel '/home/david/Deepstyle/cnn-benchmarks/VGG_ILSVRC_19_layers.caffemodel'

It seems to load and begin the process but here is an example of the error I receive:

![image](https://cloud.githubusercontent.com/assets/16936205/23995537/eb636116-0a41-11e7-9592-6b54336b36ad.png)

Any help would be greatly appreciated! I can't seem to locate the /tmp directory listed (to resolve error 'cannot open <> in mode w')

David

**Comment by jcjohnson** [comment]
You need to add the flag `-output_t7` giving the path where the output should be written.

**Comment by DavidFreebairn** [comment]
Thank you! Just added the flag as -output_t7 vgg19.t7
