### ISSUE TITLE
Speed comparison with different implement frameworks 

### ISSUE THREAD

**Issue by tumitx** [jcjohnson/cnn-benchmarks#3]
As you stated that the Alexnet is implemented from caffe, while Resnets are implemented from torch.

Is it a fair comparison about the speed?

**Comment by jcjohnson** [comment]
The AlexNet (and VGG-16 and VGG-19) models were trained in Caffe, but for the benchmark the models were converted to Torch using [loadcaffe](https://github.com/szagoruyko/loadcaffe); after conversion they are composed of normal Torch layers and are absolutely comparable to ResNet models that were trained using Torch.
