### ISSUE TITLE
meaning of (nn)

### ISSUE THREAD

**Issue by VincentChong123** [jcjohnson/cnn-benchmarks#5]
Hi Justin,

May I know what does "(nn)" mean in your table, for example TITAN X (nn)?

Thank you.

**Comment by jcjohnson** [comment]
That means that we are using the [torch/nn](https://github.com/torch/nn) backend for convolutions instead of [cuDNN](https://github.com/soumith/cudnn.torch).

**Comment by VincentChong123** [comment]
Noted with thanks!
